spring.application.name=POS
server.port=9102

# Database Connection (Inabaki na IP yako)
# Nimeongeza parameta za rewrite na prepStmts ili kuongeza kasi ya kutuma data kwenye network
spring.datasource.url=jdbc:mariadb://192.168.100.100:3306/posservice?rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Setting for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# PERFORMANCE BOOST
# Batching inasaidia SalesItems nyingi kuingia kwa mpigo mmoja badala ya moja moja
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Zima logs za ndani ili processor isitumie nguvu nyingi ku-print
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
spring.jpa.open-in-view=false

# HIKARI POOL TUNING (Optimization kwa ajili ya Network IP)
# Tunapunguza timeouts ili kama kuna mkwamo wa network, connection ijisafishe haraka
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.hikari.auto-commit=true

# HIBERNARE FLUSHING STRATEGY
# Hii inalazimisha data iandikwe (flush) mara tu baada ya muamala kukamilika
spring.jpa.properties.hibernate.flushMode=ALWAYS
